server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  flyway:
    validate-on-migrate: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        service: ${spring.application.name}
        namespace: da3fc902-1db6-43e2-afc5-314500fcbf14
        group: DEFAULT_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        namespace: da3fc902-1db6-43e2-afc5-314500fcbf14
        group: AUTH_GROUP

  config:
    import:
      - nacos:auth-service.yaml?group=AUTH_GROUP&refreshEnabled=true
      - nacos:auth-service-dev.yaml?group=AUTH_GROUP&refreshEnabled=false
